sequenceDiagram
    participant browser
    participant server

    Note right of browser: POST request to the address exampleapp/new_note_spa contains the new note as JSON data containing both the content of the note (content) and the timestamp (date): <br/> { "content": "42", "date": "2025-10-24T16:12:37.788Z" }. The Content-Type: application/json header of the request tells the server that the included data is represented in JSON format
    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa
    activate server
    Note left of server: The server responds with status code 201 created. This time the server does not ask for a redirect, the browser stays on the same page, and it sends no further HTTP requests
    server-->>browser: HTTP status code: 201
    deactivate server
    Note left of server: The SPA version of the app does not traditionally send the form data, but instead uses the JavaScript code it fetched from the server